-- ============================================================
-- 由原始 DOCX 會議記錄解析成系統表單可編輯格式。
-- 來源：/Users/yikaihuang/Desktop/2627 AI委員會
-- 執行方式：貼到 Supabase SQL Editor -> Run
-- ============================================================

insert into public.meetings (
  id,
  project_id,
  title,
  meeting_date,
  summary,
  notes,
  google_meet_url,
  notes_doc_url
)
values
  ('11111111-0509-0000-0000-000000000001'::uuid, null, $title_20260509$AI委員會第一次技術會議$title_20260509$, '2026-05-09'::date, null, $notes_20260509$<!-- rotary-meeting-html-v1 -->
<!-- rotary-structured-meeting-v1 -->
<h1>AI委員會第一次技術會議</h1>
<h2>一、會議資訊</h2><table><tbody><tr><th scope="row">會議名稱</th><td>AI委員會第一次技術會議</td></tr><tr><th scope="row">會議時間</th><td>2026-05-09</td></tr><tr><th scope="row">會議方式</th><td>杭州南路</td></tr><tr><th scope="row">主持人</th><td>台北永恆社 P Vivian（王沛昀）</td></tr><tr><th scope="row">與會人員</th><td>PDG APPS、IDG Computer、龍翔社 PT、龍山社 Jake、宇宙社 CP AI、旭光社 Candice、英倫社 Kent、永恆社 Vivian、正向衛星社 Jim、永心社 CP Wesley</td></tr></tbody></table>
<h2>二、會議決議</h2><h3>決議1｜AI 工作坊推動案</h3><table><tbody><tr><th scope="row">內容</th><td>AI 工作坊為第一階段優先推動項目，目的為協助執秘、社務幹部、社長及各社 AI 委員實際使用 AI，減輕社務行政負擔。<br>第一場工作坊以 AI 入門為主，聚焦新手實用操作。<br>課程內容須能實際應用於社務，不做純理論教學。<br>優先整理執秘常見社務痛點，轉為具體課程題目。<br>6月底上任前舉辦2場 (執秘一場、社長一場)，每次兩小時，全年共 14 場。<br>決 議： AI 工作坊列為第一優先執行項目。第一場以「AI 入門與執秘社務應用」為主題。<br>課程主題涵蓋：社刊製作、FB 貼文、活動紀錄、服務影音、會議紀錄、活動報名、AI Agent 等。</td></tr></tbody></table><h3>決議2｜ChatBot 扶輪問答系統推動案</h3><table><tbody><tr><th scope="row">內容</th><td>建立 3481 地區專屬扶輪問答系統，協助社友查詢扶輪相關資訊。本次確認先以 MVP（最小可行產品）方式進行(開放10人測試)，不急於全面上線。<br>第一階段需確認社友實際常問的問題，以使用情境為出發點。<br>系統應回答 3481 地區專屬資料，而非一般 AI 問答。<br>需盤點資料來源、格式、更新方式與審核機制。<br>入口管道：LINE 官方帳號。<br>需評估平台成本、使用權限及日後維護難度。<br>需防範錯誤回答、過期資料、個資洩漏及敏感議題。<br>決 議： ChatBot 先做 MVP。下次會議各負責人回報使用情境、資料來源及技術評估結果。</td></tr></tbody></table><h3>決議3｜公關發文推動案</h3><table><tbody><tr><th scope="row">內容</th><td>各社活動頻繁但缺乏固定整理與發文能量，公關發文將納入 AI 工作坊教學內容，以 AI 工具降低各社發文門檻。<br>AI 可協助各社產出 FB 貼文、社刊內容及活動紀錄初稿。<br>發文內容需保留服務故事與扶輪溫度，避免過度機械化。<br>公關發文可作為 AI 工作坊實作題目，讓學員邊學邊做。<br>PT負責協助確立公關方向與社群語氣風格。<br>決 議： 公關發文列入工作坊主題，由 PT 負責提供內容方向與貼文範例。</td></tr></tbody></table><h3>決議4｜服務影音推動案</h3><table><tbody><tr><th scope="row">內容</th><td>協助各社將服務成果轉為短影音，提升服務能見度與社會影響力。<br>各社可提供照片、影片、文字素材，由 AI 委員會協助整合。<br>先製作示範影片作為後續推廣與工作坊教學案例。<br>服務影音可納入工作坊教學，讓各社自行學習製作。<br>Jake 協助規劃服務影音流程、格式與投稿規範。<br>決 議： 先製作示範影片，不先全面推廣。示範影片完成後作為工作坊教材。</td></tr></tbody></table><h3>決議5｜扶輪會計系統推動案</h3><table><tbody><tr><th scope="row">內容</th><td>扶輪會計系統由 PDG APPS 持續開發，完成後工作坊協助教學。<br>系統目標為減輕社長、財務幹部及執秘的帳務作業負擔。<br>採自由使用原則，不強制各社導入。<br>系統完成後可於工作坊中展示並推廣使用。<br>決 議： 待PDG APPS 開發完成後討論。</td></tr></tbody></table><h3>決議6｜扶輪護照 2.0 推動案(需確認PDG意願)</h3><table><tbody><tr><th scope="row">內容</th><td>先進行功能需求盤點，不急於重啟 APP 開發。核心需求涵蓋：身分認證、帳號資料整合、職業資訊蒐集及使用誘因設計。<br>需先確認社友實際使用理由與誘因。<br>需解決社員身分認證與帳號資料整合問題。<br>需規劃各社職業資訊蒐集方式，為職業服務打基礎。<br>可與職業服務結合，提升社友使用動機。<br>未來可串接 ChatBot、活動報名、社群分享等功能。<br>決 議： 扶輪護照 2.0 先進行需求盤點，下次會議回報身分認證、帳號資料及職業資訊規劃。</td></tr></tbody></table><h3>決議7｜各社 AI 委員會對接案</h3><table><tbody><tr><th scope="row">內容</th><td>各社需指派 AI 委員作為地區對接窗口，工作坊參與、工具測試、資料收集與需求回報，均透過各社 AI 委員協助推動。<br>決 議： 由 Vivian 規劃各社 AI 委員對接方式，並擬定邀請各社指派 AI 委員之流程。<br>臨時動議一：QR Code 簽到系統與資料累積<br>QR Code 簽到系統可作為地區資料累積與社務數位化的切入點。<br>QR Code 簽到可取代紙本簽到與補簽流程，提升效率。<br>可減輕執秘統計出席資料之作業負擔。<br>地區可即時掌握各社出席狀況，利於管理。<br>本次未列為第一階段正式執行項目。<br>決 議： 列為後續評估項目，本階段暫不分派執行人。待第一階段項目推進後再行評估。</td></tr></tbody></table>
<h2>三、待辦事項 To Do</h2><table><thead><tr><th>負責人</th><th>待辦事項</th><th>期限</th><th>狀態</th></tr></thead><tbody><tr><td>PT、Candice、Kent、Vivian</td><td>規劃第一場 AI 工作坊課程大綱（含講師、流程、小幫手分工）</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>PT、Candice、Kent、Vivian</td><td>初步排定全年 12 至 14 場工作坊主題清單</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>Wesley、Vivian</td><td>整理執秘社務痛點，轉為具體可用 AI 解決之課程題目</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>IDG Computer、CP AI、Jim、Wesley</td><td>提出第一階段使用情境（社友可能會問哪些問題）Wesley執秘那段要先走，後面才有辦法拿到意見評估</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>IDG Computer、CP AI、Jim、Jake</td><td>評估 LINE、官網、扶輪護照 2.0 等入口管道</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>IDG Computer、CP AI、Jim、Jake</td><td>回報平台成本、使用權限及維護方式</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>PDG APPS</td><td>盤點可提供之扶輪及 3481 地區相關資料來源 (PDG出國暫緩一周詢問)</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>PT</td><td>提供公關發文教學方向與社群語氣建議</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>PT</td><td>準備 FB 貼文範例供工作坊使用</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>Vivian、Candice、Kent</td><td>將公關發文排入全年工作坊主題清單</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>Vivian</td><td>製作服務影音示範影片</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>Jake</td><td>規劃服務影音流程、格式與投稿規則</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>Wesley</td><td>盤點扶輪護照 2.0 功能需求清單</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>Wesley</td><td>規劃各社職業資訊蒐集方式</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>PDG APPS</td><td>提供過去系統開發經驗、技術限制與可繼承資源</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>Vivian</td><td>規劃各社 AI 委員對接方式與聯絡機制</td><td>2026/05/16</td><td>進行中</td></tr><tr><td>Vivian</td><td>擬定邀請各社指派 AI 委員之邀請方式</td><td>2026/05/16</td><td>進行中</td></tr></tbody></table>$notes_20260509$, null, null),
  ('11111111-0516-0000-0000-000000000002'::uuid, null, $title_20260516$AI委員會第二次技術會議$title_20260516$, '2026-05-16'::date, null, $notes_20260516$<!-- rotary-meeting-html-v1 -->
<!-- rotary-structured-meeting-v1 -->
<h1>AI委員會第二次技術會議</h1>
<h2>一、會議資訊</h2><table><tbody><tr><th scope="row">會議名稱</th><td>3481 地區 AI 委員會工作會議</td></tr><tr><th scope="row">會議時間</th><td>2026-05-16</td></tr><tr><th scope="row">會議方式</th><td>Zoom 線上會議</td></tr><tr><th scope="row">與會人員</th><td>IDG Computer、PT、Kent、Candice、Jack、Jake、CP AI、Vivian、Wesley</td></tr></tbody></table>
<h2>二、會議決議</h2><h3>決議1｜AI 工作坊</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Vivian</td></tr><tr><th scope="row">合作對象</th><td>PT、Candice</td></tr><tr><th scope="row">內容</th><td>AI 工作坊分為兩場：執祕場、社長場。<br>執祕場：AI 入門與執祕社務應用。<br>社長場：AI 協助社長掌握總監獎項與年度社務管理。<br>工作坊今日已有初版規劃，由 Vivian 與 PT 討論後定版。<br>先提出報名表，確認參加人數後再訂場地。<br>場地以 IEAT 會議中心或集思會議中心為主。<br>執祕場不收費，IDG 準備伴手禮。<br>執祕場日期：6/28；09:00 報到與架電腦；09:20-11:50 正式課程。<br>社長場暫定 7/12 下午辦理，收費 200 元。<br>社長、執祕訓練會，AI 委員會委員皆需出席。<br>現場需安排小幫手 6-8 位。<br>AI 委員會需準備延長線、投影筆。</td></tr></tbody></table><h3>決議2｜AI 社務系統開發</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Vivian</td></tr><tr><th scope="row">合作對象</th><td>PT、IDG、Kent</td></tr><tr><th scope="row">內容</th><td>系統名稱定為 AI 社務系統。<br>系統分為 MAIN 管理端及各社使用端。<br>AI 社務系統納入：總監獎項、年度社務總表、甘特圖、佐證資料、活動紀錄、公共形象貼文、基金捐獻、GG 案、IOU 紀錄、社友通訊錄、社友職業資料。<br>各社只能查看與更新自己社資料。<br>MAIN 管理端可查看各社更新狀況、進度、缺件及需協助事項。<br>系統開發完成後，由 Vivian 提出測試版本，PT、IDG、Kent 協助測試並提供回饋。</td></tr></tbody></table><h3>決議3｜AI 平台與雲端帳號</h3><table><tbody><tr><th scope="row">指定負責人</th><td>IDG</td></tr><tr><th scope="row">內容</th><td>採用單一入口平台作為後續系統整合方向。<br>請 IDG 評估雲端平台、系統帳號、資料庫、權限設定、資安需求、採購需求與費用。<br>IDG 評估後提出建議方案。</td></tr></tbody></table><h3>決議4｜3481 地區扶輪 Chatbot</h3><table><tbody><tr><th scope="row">指定負責人</th><td>CP AI,Jim</td></tr><tr><th scope="row">合作對象</th><td>IDG</td></tr><tr><th scope="row">內容</th><td>建置 3481 地區扶輪 Chatbot。<br>社友有任何關於扶輪的問題，皆可透過 Chatbot 查詢。<br>Chatbot 第一階段以扶輪既有資料與 3481 地區正式資料為主要知識來源，涵蓋：扶輪基本知識、3481 地區資料、地區活動資訊、總監獎項資料、社務相關規範與流程、地區既有教材、文件、簡報及公告資料。<br>請 CP AI, Jim 與 IDG 確認 Chatbot 架構，並提出初版測試。<br>Jake 作為資源／測試組，協助測試 Chatbot 問答內容、使用流程與實際社友提問情境。</td></tr></tbody></table><h3>決議5｜AI 影音工作坊</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Jake</td></tr><tr><th scope="row">合作對象</th><td>PT,Vivian</td></tr><tr><th scope="row">內容</th><td>AI 影音工作坊列為後續進階課程。<br>Jake 於 6 月底前完成 AI 影音工作坊規劃。<br>Jake 負責安排委員會首場 AI 影音工作坊。<br>規劃內容包含：課程內容、平台清單、拍攝流程、剪輯流程、現場操作 SOP、課程架構。</td></tr></tbody></table><h3>決議6｜Rotary Passport 2.0</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Wesley</td></tr><tr><th scope="row">合作對象</th><td>PT</td></tr><tr><th scope="row">內容</th><td>Rotary Passport 2.0 另案規劃。<br>Wesley 負責彙整具體需求與功能清單。<br>PT 協助確認方向、需求完整性及後續推動可行性。<br>彙整內容包含：具體需求、功能清單、專業服務資料、會員資料應用方式、隱私與授權注意事項。</td></tr></tbody></table>
<h2>三、待辦事項 To Do</h2><table><thead><tr><th>負責人</th><th>待辦事項</th><th>期限</th><th>狀態</th></tr></thead><tbody><tr><td>Vivian</td><td>統籌 AI 工作坊規劃與報名表提出</td><td>5/20前</td><td>進行中</td></tr><tr><td>Vivian／PT</td><td>討論 AI 工作坊初版規劃並定版</td><td>6/6 前</td><td>進行中</td></tr><tr><td>Vivian／Candice</td><td>依報名人數確認 IEAT 或集思會議中心場地</td><td>報名人數確認後</td><td>進行中</td></tr><tr><td>Vivian／Candice</td><td>確認 6/28 執祕場場地與流程</td><td>6/6 前</td><td>進行中</td></tr><tr><td>IDG</td><td>準備 6/28 執祕場伴手禮</td><td>6/28 前</td><td>進行中</td></tr><tr><td>Vivian</td><td>準備延長線、投影筆</td><td>6/28 前</td><td>進行中</td></tr><tr><td>Vivian／PT／Candice</td><td>找好現場小幫手 6-8 位</td><td>6/28 前</td><td>進行中</td></tr><tr><td>AI 委員會全體委員</td><td>出席 6/28 執祕場並擔任現場小幫手</td><td>6/28</td><td>進行中</td></tr><tr><td>Vivian／PT／Candice</td><td>規劃 7/12 下午社長場，社長場收費 200 元</td><td>7/12 前</td><td>進行中</td></tr><tr><td>Vivian</td><td>修正 AI 社務系統原型</td><td>5/22前</td><td>進行中</td></tr><tr><td>Vivian</td><td>將demo社友通訊錄及職業資料納入 AI 社務系統</td><td>5/22前</td><td>進行中</td></tr><tr><td>Vivian／PT／IDG／Kent</td><td>討論 AI 社務系統架構、權限、登入流程及測試需求</td><td>儘快</td><td>進行中</td></tr><tr><td>Vivian</td><td>系統開發完成後提出測試版本</td><td>完成後</td><td>進行中</td></tr><tr><td>PT／IDG／Kent</td><td>測試 Vivian 提出之 AI 社務系統並提供回饋</td><td>測試版提出後</td><td>進行中</td></tr><tr><td>IDG</td><td>評估單一入口平台、雲端平台、帳號、資料庫、權限及採購需求</td><td>6/6 前</td><td>進行中</td></tr><tr><td>CP AI Jim／IDG</td><td>確認 3481 地區扶輪 Chatbot 架構與扶輪資料來源</td><td>6/6 前</td><td>進行中</td></tr><tr><td>CP AI Jim／IDG</td><td>提出 3481 地區扶輪 Chatbot 初版測試</td><td>架構確認後</td><td>進行中</td></tr><tr><td>Jake</td><td>擔任 Chatbot 資源／測試組，協助測試問答內容與使用流程</td><td>初版提出後</td><td>進行中</td></tr><tr><td>所有委員</td><td>提供社友常見扶輪問題，協助建立 Chatbot 題庫</td><td>6/6 前</td><td>進行中</td></tr><tr><td>Jake</td><td>完成 AI 影音工作坊規劃並安排委員會首場</td><td>6 月底前</td><td>進行中</td></tr><tr><td>Wesley／PT</td><td>彙整 Rotary Passport 2.0 具體需求與功能清單</td><td>6/6 前</td><td>進行中</td></tr></tbody></table>
<h2>四、下次會議</h2><table><tbody><tr><th scope="row">時間</th><td>6 月 6 日上午 9:00</td></tr><tr><th scope="row">方式</th><td>線上會議</td></tr><tr><th scope="row">主要議題</th><td>AI 工作坊報名狀況確認、AI 社務系統架構確認版、單一入口平台評估、3481 地區扶輪 Chatbot 初版規劃、AI 影音工作坊、Rotary Passport 2.0</td></tr></tbody></table>$notes_20260516$, null, null),
  ('11111111-0606-0000-0000-000000000003'::uuid, null, $title_20260606$AI委員會第三次技術會議$title_20260606$, '2026-06-06'::date, null, $notes_20260606$<!-- rotary-meeting-html-v1 -->
<!-- rotary-structured-meeting-v1 -->
<h1>AI委員會第三次技術會議</h1>
<h2>一、會議資訊</h2><table><tbody><tr><th scope="row">會議名稱</th><td>3481 地區 AI 委員會工作會議</td></tr><tr><th scope="row">會議時間</th><td>2026-06-06</td></tr><tr><th scope="row">會議方式</th><td>線上會議</td></tr><tr><th scope="row">主持人</th><td>Vivian</td></tr><tr><th scope="row">與會人員</th><td>Vivian、PT、Candice、Jim、Wesley</td></tr><tr><th scope="row">待確認出席</th><td>Jack、AI 相關負責人、Computer／APPS 團隊</td></tr></tbody></table>
<h2>二、會議決議</h2><h3>決議1｜AI 工作坊</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Candice</td></tr><tr><th scope="row">合作對象</th><td>PT、Vivian</td></tr><tr><th scope="row">時間／進度</th><td>7 月 26 日下午 2:00－5:00</td></tr><tr><th scope="row">內容</th><td>第一場對象：社長、秘書、AI委員會成員(各社限三人)<br>第二場對象：開放所有社友報名，職密會員優先<br>AI 工作坊第一場暫定於 7 月 26 日下午 2:00－5:00 舉行，主要邀請社長與秘書長參加。<br>第一場課程以 Google 生態系統、AI 快速應用及社務工具操作為主。<br>第二場可開放所有社友報名，因場地限制，優先保留名額給職密會員。<br>PT 建議對未能參加的社長進行意向調查，不建議直接提供錄音檔。<br>報名表需加入「無法參加但有意願」選項，作為後續開課與需求統計依據。</td></tr></tbody></table><h3>決議2｜AI 影音工作坊</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Jake</td></tr><tr><th scope="row">合作對象</th><td>PT、Vivian</td></tr><tr><th scope="row">時間／進度</th><td>待 Jack 後續說明</td></tr><tr><th scope="row">內容</th><td>因 Jack 未出席本次會議，AI 影音工作坊相關討論暫緩。<br>後續由 Candice 協助跟進 Jack 的規劃進度。<br>待 Jack 補充課程內容、平台工具、拍攝與剪輯流程後，再進一步討論。</td></tr></tbody></table><h3>決議3｜AI 社務系統上雲部署</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Vivian</td></tr><tr><th scope="row">合作對象</th><td>Jim</td></tr><tr><th scope="row">內容</th><td>目前狀態：Vivian 已完成 HTML 版本<br>主要需求：打包、部署至雲端、確認安全與權限<br>Vivian 說明目前已完成 AI 社務系統 HTML 版本，但部署至雲端時遇到技術問題。<br>PT 建議 Vivian 將專案完整打包後，交由 AI 團隊工程師協助處理。<br>Jim 表示可協助系統打包與部署，但需確認資安、操作權限及後續維護方式。<br>會後由 Vivian 與 Jim 另行討論上雲、維護與指定伺服器細節。</td></tr></tbody></table><h3>決議4｜AI 平台 MVP 與雲端伺服器</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Jim</td></tr><tr><th scope="row">合作對象</th><td>CPI／Gayvin</td></tr><tr><th scope="row">內容</th><td>主要議題：MVP 後端規格、雲端伺服器租用時機<br>Jim 說明目前已與 CPI 初步討論 AI 平台 MVP 後端規格。<br>本週內需與 CPI／Gayvin 約時間，確認後端規格與實作範圍。<br>團隊傾向先確認 MVP 實作需求，再決定是否立即租用 AWS 或其他雲端主機。</td></tr></tbody></table><h3>決議5｜Rotary Passport 2.0 功能規劃</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Wesley</td></tr><tr><th scope="row">合作對象</th><td>PT、Vivian、Candice</td></tr><tr><th scope="row">內容</th><td>推動方式：功能分階段導入<br>Wesley 說明 Fusion 2.0／Rotary Passport 2.0 功能規劃。<br>規劃功能包含：權限管理、會員名單查詢、職位索引、成就紀錄、簽到系統、出席率統計、例會資料查詢及主講人查詢。<br>團隊認同功能方向，但提醒功能不宜一次過多，以免模糊扶輪護照核心概念。<br>PT 建議第一階段先做基本查詢功能，電話、Email 等個人化資訊可於第二階段再評估。<br>主講人查詢功能可先以連結導向地區官網方式處理，不一定納入第一階段系統。<br>因後續功能可能涉及既有系統、App 或平台整合，需先確認原始碼與發布流程。<br>Vivian 將聯繫 Computer、等相關負責人，確認合作與交接方式。<br>商家地圖、衛星社資訊串接、NFC 電子名片等延伸功能，待核心功能與資安確認後再評估。<br>團隊認為部分功能不宜開放給一般大眾，以避免安全與權限風險。</td></tr></tbody></table><h3>決議6｜職業分類與會員資料收集</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Wesley</td></tr><tr><th scope="row">時間／進度</th><td>7 月開始</td></tr><tr><th scope="row">內容</th><td>Wesley 將自 7 月開始收集職業分類與相關會員資料。<br>第一階段以可公開查詢、低敏感度資料為主。<br>涉及電話、Email 等個資欄位，需待第二階段確認授權與權限架構後再處理。</td></tr></tbody></table><h3>決議7｜3481 地區 AI 知識庫與 Chatbot</h3><table><tbody><tr><th scope="row">合作對象</th><td>Wesley、PT、Vivian、Candice、Jim</td></tr><tr><th scope="row">內容</th><td>主要方向：建立常見扶輪問題、題庫與資料庫<br>後續安排：與 AI 相關負責人另行開會確認<br>團隊討論建立扶輪常見問題、題庫與資料庫的可行性。<br>AI 系統可協助新社友查詢地區活動、扶輪知識與社務資訊。<br>PT 提醒目前仍屬功能假設，需等 AI 相關負責人參與後再確認實際可行性。<br>Jim 分享第一代系統經驗，認為 AI 系統對新社友與社務查詢具實際幫助。</td></tr></tbody></table>
<h2>三、待辦事項 To Do</h2><table><thead><tr><th>負責人</th><th>待辦事項</th><th>期限</th><th>狀態</th></tr></thead><tbody><tr><td>Candice</td><td>跟進 AI 影音工作坊進度，等待 Jack 後續說明</td><td>儘快</td><td>進行中</td></tr><tr><td>Jim</td><td>會後與 Vivian 討論 AI 社務系統上雲、打包、部署與維護細節</td><td>會後</td><td>進行中</td></tr><tr><td>Jim</td><td>本週內與 CPI／Gayvin 約時間，討論 AI 平台 MVP 後端規格與雲端伺服器需求</td><td>本週內</td><td>進行中</td></tr><tr><td>Vivian</td><td>確認 7 月 26 日下午 2:00－5:00 AI 工作坊場地與時間可行性，並通知相關人員</td><td>儘快</td><td>進行中</td></tr><tr><td>Vivian</td><td>設計 AI 工作坊報名表，加入「無法參加但有意願」選項</td><td>儘快</td><td>進行中</td></tr><tr><td>Vivian</td><td>跟進並催促「扶輪 2.0」會計系統儘早 release</td><td>持續追蹤</td><td>進行中</td></tr><tr><td>Vivian</td><td>將 AI 社務系統專案打包成壓縮檔交給 Jim，後續由 Jim 協助上雲部署</td><td>儘快</td><td>進行中</td></tr><tr><td>Vivian</td><td>聯繫 Computer、APPS 團隊，確認既有系統合作、原始碼與發布流程</td><td>儘快</td><td>進行中</td></tr><tr><td>Wesley</td><td>完整彙整 Rotary Passport 2.0 功能需求與權限架構</td><td>儘快</td><td>進行中</td></tr><tr><td>Wesley</td><td>將本次討論的功能與資料整理後，上傳至指定 Google 雲端硬碟</td><td>當晚</td><td>進行中</td></tr><tr><td>Wesley</td><td>自 7 月開始收集職業分類與相關資料，7 月底前完成第一批資料</td><td>7 月底前</td><td>進行中</td></tr><tr><td>全體委員</td><td>參加 7 月 26 日下午 AI 工作坊第一場活動，確保團隊統一口徑</td><td>7 月 26 日</td><td>進行中</td></tr><tr><td>Wesley／PT／Vivian／Candice／Jim</td><td>與 AI 相關負責人開會，討論扶輪常見問題、題庫與資料庫可行性</td><td>待約時間</td><td>進行中</td></tr><tr><td>Wesley／PT／Vivian／Candice</td><td>整理功能清單與優先順序，準備向 Computer／工程團隊說明並取得資源評估</td><td>儘快</td><td>進行中</td></tr></tbody></table>
<h2>四、下次會議</h2><table><tbody><tr><th scope="row">時間</th><td>6 月 20 日</td></tr><tr><th scope="row">方式</th><td>線上會議</td></tr><tr><th scope="row">主要議題</th><td>AI 工作坊進度確認、AI 社務系統上雲進度、AI 平台 MVP、Rotary Passport 2.0、3481 地區扶輪 Chatbot、AI 影音工作坊</td></tr><tr><th scope="row">需邀請人員</th><td>AI 相關負責人、Computer 團隊、APPS 團隊、Jack</td></tr></tbody></table>$notes_20260606$, null, null),
  ('11111111-0620-0000-0000-000000000004'::uuid, null, $title_20260620$AI委員會第四次技術會議$title_20260620$, '2026-06-20'::date, null, $notes_20260620$<!-- rotary-meeting-html-v1 -->
<!-- rotary-structured-meeting-v1 -->
<h1>AI委員會第四次技術會議</h1>
<h2>一、會議資訊</h2><table><tbody><tr><th scope="row">會議名稱</th><td>3481 地區 AI 委員會工作會議</td></tr><tr><th scope="row">會議時間</th><td>2026-06-20</td></tr><tr><th scope="row">會議方式</th><td>線上會議</td></tr><tr><th scope="row">主持人</th><td>Vivian</td></tr><tr><th scope="row">與會人員</th><td>IDG Computer、Vivian、Candice、Eric、Jim、Prevers、Jake、AI、 Kent、Wesley、 Tom</td></tr><tr><th scope="row">待確認出席</th><td>-</td></tr></tbody></table>
<h2>二、會議決議</h2><h3>決議1｜AI 工作坊</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Candice</td></tr><tr><th scope="row">合作對象</th><td>PT、Vivian、Kent</td></tr><tr><th scope="row">時間／進度</th><td>7 月 26 日下午 2:00－5:00</td></tr><tr><th scope="row">內容</th><td>第一場對象：社長、秘書、AI委員會成員(各社限三人)<br>第二場對象：開放所有社友報名，職密會員優先<br>辦理時間： 暫定於 7 月 26 日（14:00－17:00）舉行。<br>主要對象： 邀請各社社長及秘書長參與。<br>報名費用： 每人 500 元。<br>7/1 統一發文： 採納 PDG APPS 之建議，為利各社提前掌握活動資訊並預留行程，定於 7 月 1 日向各社統一發布公告。<br>7/18 會議布達： 將配合 7 月 18 日之社長秘書會議（社秘會），於會議現場再次宣導及公告相關報名資訊。<br>影片權益宣告： 本場次工作坊將進行全程錄影留存。惟基於維護付費學員權益之原則，該錄影檔案僅供主辦方存檔，不予對外提供。</td></tr></tbody></table><h3>決議2｜AI 影音工作坊</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Jake</td></tr><tr><th scope="row">合作對象</th><td>PT、Vivian</td></tr><tr><th scope="row">時間／進度</th><td>待 Jack 後續說明</td></tr><tr><th scope="row">內容</th><td>7/1 宣傳影片釋出： 預計於 7 月 1 日發布首支「宣揚年度主題與推動理念」影片，作為全年度專案開場。<br>影片內容涵蓋： 地區年度發展方向、AI 委員會之核心推動精神，以及倡導各社導入 AI 應用於公共關係、服務紀錄與社務運作之目的。<br>7/18 社秘會宣導： 定於 7 月 18 日之社長秘書會議（社秘會）播放該宣傳影片，藉此鼓勵各社主動報名參與影片製作計畫，並配合提供所需素材。<br>產出目標與主題： 預計每月產出 1 至 2 支短影音，內容以「各社特色亮點」或結合「扶輪月主題」（詳見群組記事本）為主。<br>作業流程與示範： 於首次社長秘書會議前，先行擬定短影音製作方向。由各社提供特色素材，交由 AI 委員會統整為腳本與影片架構，俾利於社秘會上展示示範成果與操作指引。<br>公共關係委員會： 負責蒐集各社特色資訊並協助初審影片腳本。（對接協調窗口：Prevers）<br>AI 委員會： 負責影片之實際內容製作，並統籌最終製作決定權。<br>專屬模型開發： 由 Jack 規劃訓練「扶輪影片 AI 模型」以提升影片產出效率，實際應用成效將列入後續會議追蹤。<br>工作坊主題研議： 考量專屬 AI 模型訓練之門檻較高，各社恐難以完全複製執行，後續「AI 影片工作坊」之授課主題與教學方向需另行開會討論。</td></tr></tbody></table><h3>決議3｜AI 社務系統上雲部署</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Vivian</td></tr><tr><th scope="row">合作對象</th><td>Eric</td></tr><tr><th scope="row">內容</th><td>目前狀態：Vivian 已完成 HTML 版本<br>主要需求：打包、部署至雲端、確認安全與權限<br>背景考量： 鑒於社務系統涵蓋之功能繁複且多元。<br>交辦事項： 建請 Vivian 於下週負責與 IDG Computer 召開會議，針對系統各項功能細節進行深入對接與盤點。<br>執行方向： 為加速系統導入進程並確保穩定性，請 Vivian 於前述會議中併同評估「分階段上線」之可行性。<br>測試規劃： 研議是否能率先界定「核心功能」並先行釋出，俾利提供各社儘早進行實機測試與基礎使用。</td></tr></tbody></table><h3>決議4｜扶輪ChatBot</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Jim</td></tr><tr><th scope="row">合作對象</th><td>CP AI／Gayvin</td></tr><tr><th scope="row">內容</th><td>主要議題：MVP 後端規格、雲端伺服器租用時機 建立常見扶輪問題、題庫與資料庫<br>主機環境： 專案初期之系統建置，預計先調用（或暫借）CP AI 公司之主機資源作為運行環境。<br>上線目標： 定於 7 月 3 日正式釋出第一版 MVP（最小可行性產品），俾利接續展開各項實機測試作業。<br>Vivian： 負責對接並彙整「扶輪總會」端之相關文獻與資料。<br>IDG Computer： 負責撈取並提供「地區網站」歷年之數位建檔資料。</td></tr></tbody></table><h3>決議5｜Rotary Passport 2.0 功能規劃</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Wesley</td></tr><tr><th scope="row">合作對象</th><td>PT、Vivian、Candice</td></tr><tr><th scope="row">內容</th><td>推動方式：功能分階段導入<br>背景考量： 鑒於Rotary Passport 2.0涵蓋之功能繁複且多元。<br>交辦事項： 建請 Wesley和Vivian 於下週負責與 IDG Computer 召開會議，針對系統各項功能細節進行深入對接與盤點。</td></tr></tbody></table><h3>決議6｜職業分類與會員資料收集</h3><table><tbody><tr><th scope="row">指定負責人</th><td>Wesley</td></tr><tr><th scope="row">時間／進度</th><td>7 月開始</td></tr><tr><th scope="row">內容</th><td>Wesley 將自 7 月開始收集職業分類與相關會員資料。<br>第一階段以可公開查詢、低敏感度資料為主。<br>涉及電話、Email 等個資欄位，需待第二階段確認授權與權限架構後再處理。</td></tr></tbody></table>
<h2>三、待辦事項 To Do</h2><table><thead><tr><th>負責人</th><th>待辦事項</th><th>期限</th><th>狀態</th></tr></thead><tbody><tr><td>Candice</td><td>監控 Jim 團隊 MVP 開發進度,協調下次會議時間,確保 7 月 3 日有可展示的版本</td><td>儘快</td><td>進行中</td></tr><tr><td>Vivian</td><td>跟總監溝通 7 月 26 日工作坊的時間及相關事宜,並推動總監對工作坊內容的確認與 release</td><td>下週</td><td>進行中</td></tr><tr><td>Jim</td><td>本週內與 CPI／Gayvin 約時間，討論 AI 平台 MVP 後端規格與雲端伺服器需求</td><td>本週內</td><td>進行中</td></tr><tr><td>Vivian</td><td>確認 7 月 26 日下午 2:00－5:00 AI 工作坊場地與時間可行性，並通知相關人員</td><td>儘快</td><td>進行中</td></tr><tr><td>Candice</td><td>設計 AI 工作坊報名表，加入「無法參加但有意願」選項</td><td>儘快</td><td>進行中</td></tr><tr><td>Vivian</td><td>聯繫 PDG/總會,確認是否有可上傳的資料庫(PDF 或入口)可加入雲端,並負責總會部分的資料收集</td><td>下次會議前</td><td>進行中</td></tr><tr><td>Vivian</td><td>跟進並催促「扶輪 2.0」會計系統儘早 release</td><td>持續追蹤</td><td>進行中</td></tr><tr><td>Wesley</td><td>向總監再次確認 2.0 項目相關事項,並匯報最新進展</td><td>下週</td><td>進行中</td></tr><tr><td>Wesley</td><td>自 7 月開始收集職業分類與相關資料，7 月底前完成第一批資料</td><td>7 月底前</td><td>進行中</td></tr><tr><td>全體委員</td><td>參加 7 月 26 日下午 AI 工作坊第一場活動，確保團隊統一口徑</td><td>7 月 26 日</td><td>進行中</td></tr><tr><td>Wesley／PT／Vivian／Candice／Jim</td><td>與 AI 相關負責人開會，討論扶輪常見問題、題庫與資料庫可行性</td><td>待約時間</td><td>進行中</td></tr><tr><td>Wesley／PT／Vivian／Candice</td><td>整理功能清單與優先順序，準備向 Computer／工程團隊說明並取得資源評估</td><td>儘快</td><td>進行中</td></tr></tbody></table>
<h2>四、下次會議</h2><table><tbody><tr><th scope="row">時間</th><td>尚未定案</td></tr><tr><th scope="row">方式</th><td>線上會議</td></tr><tr><th scope="row">主要議題</th><td>AI 工作坊進度確認、AI 社務系統上雲進度、AI 平台 MVP和3481 地區扶輪 Chatbot、Rotary Passport 2.0、、AI 影音工作坊</td></tr><tr><th scope="row">需邀請人員</th><td>AI 相關負責人、Computer 團隊、APPS 團隊、Jack</td></tr></tbody></table>$notes_20260620$, null, null)
on conflict (id) do update
set
  project_id = excluded.project_id,
  title = excluded.title,
  meeting_date = excluded.meeting_date,
  summary = excluded.summary,
  notes = excluded.notes,
  google_meet_url = excluded.google_meet_url,
  notes_doc_url = excluded.notes_doc_url;
